server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}

        - id: user-service
          uri: http://${USER_SERVICE_HOST:localhost}:8082
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

        - id: chat-service
          uri: http://${CHAT_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /api/chat/${segment}

        - id: chat-websocket
          uri: ws://${CHAT_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws/(?<segment>.*), /ws/${segment}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-environment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.chat: DEBUG
